[package]
name = "project_tortoise"
version = "0.1.0"
authors = ["dantink <dantink@sahajsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
queues = "1.1.0"
bufstream = "0.1.4"
